install.packages("shinyIncubator", repos="http://cran.rstudio.com/")
install.packages("markdown", repos="http://cran.rstudio.com/")
install.packages("whisker", repos="http://cran.rstudio.com/")
install.packages("scales", repos="http://cran.rstudio.com/")
install.packages("Hmisc", repos="http://cran.rstudio.com/")
install.packages("plyr", repos="http://cran.rstudio.com/")
install.packages("dplyr", repos="http://cran.rstudio.com/")
install.packages("tidyr", repos="http://cran.rstudio.com/")
install.packages("lubridate", repos="http://cran.rstudio.com/")
install.packages("ggplot2", repos="http://cran.rstudio.com/")
install.packages("qcc", repos="http://cran.rstudio.com/")

# sudo apt-get install libcurl4-openssl-dev
install.packages("httr", repos="http://cran.rstudio.com/")
install.packages("rversions", repos="http://cran.rstudio.com/")
install.packages("RCurl", repos="http://cran.rstudio.com/")
install.packages("curl", repos="http://cran.rstudio.com/")
install.packages("devtools", repos="http://cran.rstudio.com/")
library(devtools)
devtools::install_github("ropensci/ckanr")
