install.packages("shinyIncubator")
install.packages("markdown")
install.packages("whisker")
install.packages("scales")
install.packages("Hmisc")
install.packages("plyr")
install.packages("dplyr")
install.packages("tidyr")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("qcc")

install.packages("httr")
install.packages("rversions")
install.packages("RCurl")
install.packages("curl")
install.packages("devtools")

devtools::install_github("ropensci/ckanr")
